CREATE SEQUENCE IF NOT EXISTS SEQ_User START WITH 1 INCREMENT BY 1;

CREATE TABLE User (
	ID BIGINT PRIMARY KEY,
	FIRSTNAME VARCHAR(200),
	LASTNAME VARCHAR(200),
	ADDRESS VARCHAR(200),
	ZIPCODE VARCHAR(200),
	CITY VARCHAR(200),
	COUNTRY VARCHAR(200),
	SUPPLIERID BIGINT
)